### ISSUE TITLE
It is not possible to set "Mining productivity bonus" for Miners

### ISSUE THREAD

**Issue by flameSla** [DanielKote/Foreman2#1]
It is not possible to set "Mining productivity bonus" for Miners

**Comment by DanielKote** [comment]
Point. I completely forgot about it. Will add it to the next feature list.

**Comment by DanielKote** [comment]
Taken care of in the latest version. There is now a productivity bonus that you can set for each miner (and copy between them), as well as an advanced option to enable productivity bonuses for all recipes.
