### ISSUE TITLE
Profile Importer "Mod Inconsistency Detected"

### ISSUE THREAD

**Issue by Fallout301** [DanielKote/Foreman2#10]
When importing from a modded factorio game, I got this error
![2021-11-09_11-54-06](https://user-images.githubusercontent.com/2678873/140968909-a878ac83-34c0-4bd7-a04d-ccabe8aac12e.png)
After disabling and testing one by one, I narrowed it down to Yuoki Industries specifically that is that problem.

After further testing, I figured out what the issue is when importing with Yuoki Industries. The name of the zip file is what seems to trip up the importer.

Yuoki's mod is originally named: ```Yuoki_1.1.02.zip``` once the file is renamed to:  ```Yuoki_1.1.2.zip``` it works. The filename issue works for any mod as far as I can tell, tried to break it the other way around by putting a 0 after, and then factorio crashed with a name mismatch 😆 guess I should have expected that one. Thank you for keeping Foreman alive and I hope this information proves helpful!

Foreman version: v2.0-dev.9
Factorio version: Steam Release 1.1.46
OS: Windows 10 Pro

Steps To Recreate:
Step 1: Install and enable Yuoki Industries
Step 2: Attempt to import profile in Foreman 

Steps To Fix:
Step 1: rename ```Yuoki_1.1.02.zip``` to ```Yuoki_1.1.2.zip```
Step 2: Done.

The logs did not seem particularly insightful in relation to this issue, but I attached them anyway.

[errorlog.txt](https://github.com/DanielKote/Foreman2/files/7506616/errorlog.txt)
Pre file rename:
[factorio-current.log](https://github.com/DanielKote/Foreman2/files/7506619/factorio-current.log)
 Post file rename:
[factorio-current.log](https://github.com/DanielKote/Foreman2/files/7506748/factorio-current.log)

**Comment by DanielKote** [comment]
Right - I kind of assumed that leading zeros werent accepted in mod versions seeing as how I didnt come across any mod that had them. Naturally I didnt spot Yuoki's mods.
Installed the Yuoki mod, reproduced the error, fixed it, ensured it works with Yuoki mods now.

Bug fixed, will be pushed with next release in a couple days, but for now if you want you can grab the source code and compile it.
