### ISSUE TITLE
Steam consumption

### ISSUE THREAD

**Issue by AbyssalLayer** [DanielKote/Foreman2#101]
when i try to make this recipe
![image](https://github.com/user-attachments/assets/74ca61e3-e8ce-4abb-b173-113e3107523f)
it needs pY fluid mining drill, and this part shows me that i need 100 steam/s
![image](https://github.com/user-attachments/assets/af8fd1a3-dc05-4c1b-937b-b31aa72e7912)
but game says that i need only 
![image](https://github.com/user-attachments/assets/20f06860-68a9-4de0-a00e-741836135030)
10 steam/operation and it do 0.5 operations/s so its 20 steam/s
and if you use rate calculator it says that 
![image](https://github.com/user-attachments/assets/9c612e60-f2af-4ffa-ab30-182fa942641e)

**Comment by DanielKote** [comment]
Yes, this seems to be an issue with my understanding of fluid_amount in mineable_properties of entity prototypes in factorio. The same issue is present in vanilla for sulfuric acid for nuclear ore, so I will just set it up to divide the value by 10 upon import.
Will be fixed in next release.

**Comment by AbyssalLayer** [comment]
Ty <3
