### ISSUE TITLE
Shown Quality percentage is off by a factor of 10 compared to in-game

### ISSUE THREAD

**Issue by gillett-hernandez** [DanielKote/Foreman2#103]
a base tier quality 1 module increases quality by 1%, but the shown quality in an assembler or miner is 10% when said module is selected
this discrepancy doesn't appear to affect the output quantities of higher tier quality items.

this commit fixes it, though it might not be the best way to fix it
https://github.com/gillett-hernandez/Foreman2/commit/eb383aee965fd2ac05873906f77d9ba4a9a75b8e

**Comment by DanielKote** [comment]
Yes, this is working as intended.
Factorio includes an internal value for the 'chance to go from one quality to the next' which is set to 10% for all qualities, but is editable by the modding community to be different for each quality. As such the value shown in foreman reflects the actual module bonus and disregards this additional multiplier, though this multiplier is accounted for when calculating recipe results.
I thought about including the 10% multiplier in the displayed bonus number, which would make it more in-line with vanilla factorio, but it would cause issues if the multiplier is different for a given quality (visually).

For now I think the best option is to just leave it as is, with perhaps a mouse-over note listing the actual percentages for each quality.

I will add this to my list of possible QOL updates, but no changes are expected at this time.
