### ISSUE TITLE
Add the ability to find out the version of the program

### ISSUE THREAD

**Issue by flameSla** [DanielKote/Foreman2#12]
I don't remember, I have version 2.9 or 2.10 installed, how do I find out the version of the program?

**Comment by DanielKote** [comment]
If you drag from an item to create a new node while holding down ctrl it will automatically place down a passthrough node in version 2.10 but will ask you to select the recipe (same as if you didnt hold down ctrl) in version 2.9.
You are of-course correct. I will see about adding proper versioning to the program so you can right-click options to check the version without having to guess.
