### ISSUE TITLE
QoL changes - save

### ISSUE THREAD

**Issue by mrozpara** [DanielKote/Foreman2#13]
Hi,

Would it be possible to add following features:
- warning before closing unsaved changes?
- save/save as options - to be able to save quickly under the same name without having to select file and confirm overwrite?

thanks

**Comment by DanielKote** [comment]
Currently the program doesnt keep track in terms of which file is opened - instead when you open a save file it basically imports it into the graph. Implementing saves properly is something on the to-do list, though it has a few nuances that make it harder to implement than may seem right off the bat.

**Comment by DanielKote** [comment]
Done. I added in save file persistence, so there is now a save-as along with save, and if you are loading/quitting with changes having been made (or an untitled graph) it will ask for confirmation / save of graph prior to continuing. Will be released as part of Dev.12 in the next couple days.

**Comment by DanielKote** [comment]
Dev-12 has been released.
