### ISSUE TITLE
Allow graph navigation via WASD.

### ISSUE THREAD

**Issue by antrobot1234** [DanielKote/Foreman2#17]
as a person on a laptop, it is frustrating to have to click in the corner of my trackpad and get a tiny movement area as a result. I feel like it would be much simpler if i could pan the camera with WASD. I would also appreciate speed modifier keys (such as shift and control) that could speed up and slow down the pan respectively.

**Comment by MartinKlefas** [comment]
+1

**Comment by mrozpara** [comment]
I've added WASD movement to my version of Foreman:
https://github.com/mrozpara/Foreman2

(I've used to be developer ages ago... therefore my own version is not so stable, however... ;))
