### ISSUE TITLE
Machine count display within node graphic

### ISSUE THREAD

**Issue by antrobot1234** [DanielKote/Foreman2#19]
Fairly simple request, but I believe it would be nice to have a number somewhere within a node (such as beneath the machine graphic) to designate how many machines the node requires without having to enter the node itself.

**Comment by DanielKote** [comment]
Open up settings -> graph options and switch the level of detail from low to either medium (adds # of machines, modules, and beacons to each node) or high (also adds productivity, speed, & efficiency percentage values)
