### ISSUE TITLE
More information about over/underproduction.

### ISSUE THREAD

**Issue by CricketBr** [DanielKote/Foreman2#24]
It's not clear what is being over/under produced unless I add up each amount. It looks like the affected nodes have two numbers for that product, but I can't find an explanation in the manual.

**Comment by DanielKote** [comment]
I have added a note about this in the readme (which will now be available through a help button within the app). The way the simulation works is that no item can ever be under-produced (or in other words items will not 'appear' from nowhere). If the required quantities arent met (ex: you set exactly 1 assembler but require a ton more items to be produced) then the solution will show only the amount capable of being produced with a red border to signify that it is less than the amount asked for.

In terms of over-production the border will change to be golden and two numbers will appear - the top one representing the amount of the item that will be consumed by recipes later on down the line while the bottom one represents the actual amount being produced. So if you see 4 / 10 with 4 on top and 10 on the bottom then you know that the recipe & assembler will produce 10 of the item but only 4 of those will be consumed by later processes. That means that 6 will be stockpiled in your buffer (assuming you have one) until the system clogs up.
