### ISSUE TITLE
All types of filled barrels are not showing in recipes, even with the vanilla game preset

### ISSUE THREAD

**Issue by Mokmo** [DanielKote/Foreman2#28]
The fill and empty barrel recipes are not imported in the presets. 
In Vanilla game, all I get when searching for recipes using or making Empty Barrels is the barrel making one and cliff explosives.
In Space Exploration, It will show the barrel-making recipe plus those that use it: cliff explosives, rocket science packs, scrapping and reprocessing. There are 20 fill barrel, 20 empty barrel and 7 delivery capsule recipes missing because of the same problem

**Comment by MForster** [comment]
Have you tried the "Load barreling crating recipes (DEV)" setting?

**Comment by Mokmo** [comment]
Well well well, guess I didn't look thoroughly.

**Comment by arik123** [comment]
This same problem just happened to me, I would suggest making it enabled by default, so this does not happen to more people.

**Comment by krypt-lynx** [comment]
Also happened to me

**Comment by DanielKote** [comment]
I have added a help / git-repository button to the app in order to quickly be able to open up the readme page. From there issues like this should be quick to be resolved simply by searching for keywords like 'barrel'.
