### ISSUE TITLE
Issue with big number of components

### ISSUE THREAD

**Issue by mrozpara** [DanielKote/Foreman2#43]
In case of PY and some recepies the size of BaseNodeElement is too big - not able to drag/tooltip not being displayed.

Solution:
modify: public BaseNodeElement GetNodeAtPoint(Point point) (ProductionGraphViewer) initial size of search area:
Rectangle initialCheckZone = new Rectangle(point.X - 400, point.Y - 150, 800, 300);

**Comment by bizarro420** [comment]
Yeah with some of the later science packs cant link to the outer items. Seems to be around 11/12 items before unable to click on outermost most ones

**Comment by mrozpara** [comment]
as quick work-around: link/click on items closer to middle and later move connected source/passtrough to the side. It will change order of items and enable other items
