### ISSUE TITLE
Space Exploration 0.6 not working properly

### ISSUE THREAD

**Issue by Dromader2137** [DanielKote/Foreman2#44]
My satelite telemetry recipe is: 0xsatelite + 100xrocketPart = 0xsatelite telemetry ,
which should be: 1xsatelite + 100xrocketPart = 100xsatelite telemetry

**Comment by mrozpara** [comment]
quickest fix - go to proper "pjson" file in Preset folder and change the recipe manualy...

**Comment by Dromader2137** [comment]
i don't have a .pjson file in Preset directory.

**Comment by mrozpara** [comment]
What files do you have in that folder? There should be a file with the same name as your Foreman preset/configuration. Can you share that file?

**Comment by Dromader2137** [comment]
i have fixed the whole issue by editing the fjson file of my graph. thanks for help :)

**Comment by mrozpara** [comment]
recipe is copied from preset file (pjson) to graph file (fjson) - so with new graph you will have to do it again. But now you know how to do it ;)
