### ISSUE TITLE
Missing Recipes for SE

### ISSUE THREAD

**Issue by dneff1895** [DanielKote/Foreman2#45]
Does not pull all of the recipes for everything, for example I'm missing crushed vulcanite and enriched vulcanite recipes. It only shows Delivery cannon recipes.

**Comment by mrozpara** [comment]
I think that this is connected to "wrong icon" issue - see [https://github.com/gillett-hernandez/Foreman2/discussions/4](Discussion)
After import of SE preset I can see 2 recipes for crushed vulcanite - but marked with stone and sand icons. Could you double check it?

**Comment by dneff1895** [comment]
Yeah, that's correct, I didn't check thoroughly enough. Apologies, I'll have to triple check next time. I really like this program though.
