### ISSUE TITLE
Cannot make Py mods work with Foreman 2.0 dev12

### ISSUE THREAD

**Issue by TheInfinityUser** [DanielKote/Foreman2#49]
I have tried several times to load Pyanodons mods with/without QOL mods and Foreman has failed every time with the following error -
[errorExporting.txt](https://github.com/DanielKote/Foreman2/files/10199257/errorExporting.txt)
This collection of mods works without any errors when I load the game.

**Comment by mrozpara** [comment]
try using Foreman fork: [https://github.com/gillett-hernandez/Foreman2](https://github.com/gillett-hernandez/Foreman2)

**Comment by TheInfinityUser** [comment]
Thank you, the fork fixed the issue!
