### ISSUE TITLE
import fails with seablock

### ISSUE THREAD

**Issue by JurkoDev** [DanielKote/Foreman2#50]
so the import fails wiith 
![image](https://user-images.githubusercontent.com/50539591/222969245-f31effa9-91d5-4f78-9b1a-f0e82128ec68.png)
i have seablock modpack i found somewhere
modlist, log of the foreman backround run and log of a normal open too menu screen
[mod-list.json](https://github.com/DanielKote/Foreman2/files/10892144/mod-list.json.txt)
[factorio-current-foreman.log](https://github.com/DanielKote/Foreman2/files/10892147/factorio-current-foreman.log)
[factorio-current-normalopen.log](https://github.com/DanielKote/Foreman2/files/10892148/factorio-current-normalopen.log)

**Comment by mrozpara** [comment]
try the version from fork: https://github.com/gillett-hernandez/Foreman2

**Comment by DanielKote** [comment]
Should be fixed in the next version
