### ISSUE TITLE
import preset failing due to error message "there is already an item with the same key"

### ISSUE THREAD

**Issue by Thiske0** [DanielKote/Foreman2#7]
I'm facing an error wit error message "Er is al een item met dezelfde sleutel toegevoegd" or translated from dutch "there is already an item with the same key".
![image](https://user-images.githubusercontent.com/12071982/140614370-b6512788-e32f-4ce5-bce9-c3573a567f42.png)
Ignoring this error makes the preset window stop loading at 96%
![image](https://user-images.githubusercontent.com/12071982/140614441-e693df46-0561-4df2-8b2b-65302c1455c5.png)

full error message:
[error.txt](https://github.com/DanielKote/Foreman2/files/7490700/error.txt)

i'm playing pY and using a lot of mods.
factorio (version 1.1.42) config:
[config.ini.txt](https://github.com/DanielKote/Foreman2/files/7490711/config.ini.txt)
modlist:
[mod-list.json.txt](https://github.com/DanielKote/Foreman2/files/7490713/mod-list.json.txt)

**Comment by DanielKote** [comment]
Ok, I unfortunately could not reproduce the issue even after installing all the listed mods, but the error message helped out. The import should work fine in the next version (dev.7).
Update: Issue was reproduceable - just had to double check the mods. Dev.7 (once its out) will have the fix.
