### ISSUE TITLE
Error with instrument-after-data

### ISSUE THREAD

**Issue by Ldmf** [DanielKote/Foreman2#75]
I have a problem with the import form the foremanexport 

Error Log Foreman

[errorlog.txt](https://github.com/DanielKote/Foreman2/files/12909019/errorlog.txt)
[errorExporting.json](https://github.com/DanielKote/Foreman2/files/12909017/errorExporting.json)

Mod-List from factorio

[mod-list.json](https://github.com/DanielKote/Foreman2/files/12909018/mod-list.json)

Curentlog Factorio

[factorio-current.log](https://github.com/DanielKote/Foreman2/files/12909028/factorio-current.log)

if more info is needed i will try and provide them

**Comment by shadoworld56** [comment]
not sure anyone actively works on this anymore. I fixed this issue by changing line 24
`ExportParameter('icon', (icon == nil) and 'null' or '"'..icon..'"', true, ',', 4)`
to 
`ExportParameter('icon', (icon == nil) and 'null' or '"'..tostring(icon)..'"', true, ',', 4)`
as the tostring function seems to clear up the issue.

Edit: forgot to include where to find the files for anyone else having issues. 
`Foreman 2 Folder\Release\Mods\foremanexport_1.0.0\instrument-after-data.lua`

This seems to clear up issues with foreman 2 failing to export factorio data with some mods installed.

**Comment by Ldmf** [comment]
it works with all the mods exept SE

the error is now

<<<END-EXPORT-P1>>>
   3.049 Checksum for core: 2152183905
   3.049 Checksum of base: 2056641960
   3.049 Checksum of simhelper: 0
   3.049 Checksum of aai-containers: 1506515135
   3.049 Checksum of aai-signal-transmission: 117271088
   3.049 Checksum of alien-biomes: 4075303506
   3.049 Checksum of foremanexport: 3412107626
   3.049 Checksum of informatron: 3677685015
   3.049 Checksum of jetpack: 705397686
   3.049 Checksum of robot_attrition: 3717203635
   3.049 Checksum of shield-projector: 1559000050
   3.049 Checksum of space-exploration-graphics: 0
   3.049 Checksum of space-exploration-graphics-2: 0
   3.049 Checksum of space-exploration-graphics-3: 0
   3.049 Checksum of space-exploration-graphics-4: 0
   3.049 Checksum of space-exploration-graphics-5: 0
   3.049 Checksum of space-exploration-menu-simulations: 1283024780
   3.049 Checksum of aai-industry: 2584868198
   3.049 Checksum of space-exploration: 533341966
   3.049 Checksum of space-exploration-postprocess: 1055654810
   3.533 Error Util.cpp:86: Error while loading entity prototype "se-gate-fragment-14-a" (simple-entity): Sprite height outside valid range (1-2048).

At ROOT.simple-entity.se-gate-fragment-14-a.picture.layers[0].hr_version
Modifications: Space Exploration

------------- Error -------------
Error while loading entity prototype "se-gate-fragment-14-a" (simple-entity): Sprite height outside valid range (1-2048).

At ROOT.simple-entity.se-gate-fragment-14-a.picture.layers[0].hr_version
Modifications: Space Exploration
---------------------------------
All done.
==============================================

**Comment by DanielKote** [comment]
Version 2.0 of factorio has changed things. issue closed due to extensive modification of instrument-after-data.
