### ISSUE TITLE
Feature request: accessibility + dark mode

### ISSUE THREAD

**Issue by i-make-robots** [DanielKote/Foreman2#85]
Accessibility: Being able to zoom in is great.  How about increasing icon size?  in some mods I have many very similar tiny icons to choose from and my old eyes struggle to tell the difference.

Dark mode: also for my eyeballs, the all-white background wears on the retina.  A choice for a dark grey background would be awesome.

Thank you!

**Comment by DanielKote** [comment]
Both options should be added in the next release (dark mode & increased icon size for recipe/item chooser panel)
