### ISSUE TITLE
Space Age Compatibility

### ISSUE THREAD

**Issue by lilac-eclipse** [DanielKote/Foreman2#88]
Hi!

Are there any plans to update this to be compatible with space age?

Thanks!

**Comment by DanielKote** [comment]
Yes, I am currently working on updating foreman to be compatible with space age, with the plan being to push forward an initial update to get it working without quality changes and then focus on the rather large project of adding in quality in the followup update.
Unfortunately there has been a rather significant change to the handling of variables in LUA, so its taking longer than I expected.

**Comment by DanielKote** [comment]
The latest update (2.2.15) is now fully compatible with Space Age!
This means that the following are fully supported:
1. quality
2. spoilage
3. planting
