### ISSUE TITLE
[Bug][2.2 dev14] Wrong field addressed in instrument-control.lua for 2.x branch of Factorio

### ISSUE THREAD

**Issue by SillyBits** [DanielKote/Foreman2#89]
**Description:**
When trying to import a Pyandon pack with current Factorio 2.0.11, error following is raised:
```
   0.000 Error Util.cpp:81: The scenario level caused a non-recoverable error.
Please report this error to the scenario author.

Error while running event level::on_nth_tick(1)
__foremanexport__/instrument-control.lua:508: attempt to index field 'burner_prototype' (a nil value)
stack traceback:
	__foremanexport__/instrument-control.lua:508: in function 'ExportEntities'
	__foremanexport__/instrument-control.lua:687: in function <__foremanexport__/instrument-control.lua:672>

------------- Error -------------
The scenario level caused a non-recoverable error.
Please report this error to the scenario author.

Error while running event level::on_nth_tick(1)
__foremanexport__/instrument-control.lua:508: attempt to index field 'burner_prototype' (a nil value)
stack traceback:
	__foremanexport__/instrument-control.lua:508: in function 'ExportEntities'
	__foremanexport__/instrument-control.lua:687: in function <__foremanexport__/instrument-control.lua:672>
---------------------------------
```

**Cause:**
After inspection, I found the wrong field is being addressed in line 508, `entity.burner_prototype` instead of `entity.fluid_energy_source_prototype`. 

**Fix:**
Editing this line to use `entity.fluid_energy_source_prototype` instead resolved the import error and preset was generated without further issues.

**Comment by DanielKote** [comment]
Thank you, the fix will be included in the next publish version (along with making save files work again...)
Wasnt aware that Py mods have already been updated - guess I can use them as a perfect 'worst case scenario' test case again - was just running tests on vanilla until now.
