### ISSUE TITLE
Game is starts freely but Foreman2 gives error

### ISSUE THREAD

**Issue by AbyssalLayer** [DanielKote/Foreman2#90]
I try to load my mod set in program as preset but it gives an error like this (yes i can start game manualy and play it)
![image](https://github.com/user-attachments/assets/d7eb84e9-b2db-49fc-9f52-b9b4abe8b1fa)
my mod list is mostly Py 
![image](https://github.com/user-attachments/assets/d349e0f8-ce0c-45b0-a5f5-8d651d637a05)
![image](https://github.com/user-attachments/assets/60840e83-a0a6-4279-9b37-7b7b89782df7)
![image](https://github.com/user-attachments/assets/daf5d179-bdac-4d6f-9f2e-c703f4295d96)

**Comment by DanielKote** [comment]
Could you please try again and when you get this issue go into the foreman folder and upload the errorlog.txt and/or errorExporting.json files? Foreman is still in the midst of the 2.0 update, so the current downloadable version is more of a 'day-1' release that works with base vanilla 2.0 (not even SA), but I will see what I can do.

**Comment by AbyssalLayer** [comment]
Sure, im happy to help with this :3
[errorExporting.json](https://github.com/user-attachments/files/17576892/errorExporting.json)
[errorlog.txt](https://github.com/user-attachments/files/17576894/errorlog.txt)

**Comment by DanielKote** [comment]
Ah, yes - this issue has already been brought up and fixed, and will be included in the next release.
For now if you could open the file mods/foremanexport_2.0.0/instrument-control.lua and search for:
`for pollutant, quantity in pairs(entity.burner_prototype.emissions_per_joule) do`
and replace it with
`for pollutant, quantity in pairs(entity.fluid_energy_source_prototype.emissions_per_joule) do`
It should be on line 508.
Please try this and see if it helps.

**Comment by DanielKote** [comment]
Should be now fixed in the latest release (2.2.15)

**Comment by AbyssalLayer** [comment]
> Should be now fixed in the latest release (2.2.15)

Ye its working now. Ty <3
