### ISSUE TITLE
Unable to load py mod

### ISSUE THREAD

**Issue by yxm1117** [DanielKote/Foreman2#91]
Only a simple py mod，The game loading mod can start normally。
<img width="358" alt="d809d2b4c03e3c111e98547da6ad55f" src="https://github.com/user-attachments/assets/c5fa33fe-6c7e-4fe9-a0e9-b45f34caef02">
![image](https://github.com/user-attachments/assets/6a55393f-a7b9-45d7-bc96-d6a9e667afbc)
![image](https://github.com/user-attachments/assets/00765ca8-990b-4c52-a906-e1647cb1155b)
[errorlog.txt](https://github.com/user-attachments/files/17583051/errorlog.txt)
[errorExporting.json](https://github.com/user-attachments/files/17583098/errorExporting.json)

**Comment by DanielKote** [comment]
Should be taken care of in the latest release (2.2.15), I tried it with the standard Py collection and it worked.
