### ISSUE TITLE
Modules and beacons not populating on left click of assemblers with Py

### ISSUE THREAD

**Issue by napceps** [DanielKote/Foreman2#94]
Usually when I left click an assembler, a menu like this comes up:
![image](https://github.com/user-attachments/assets/4d094e94-5f71-480c-b568-7d104cf7a1d1)
However, with Py mods installed, when I left click the moss/wood buildings, modules don't get populated:
![image](https://github.com/user-attachments/assets/80719f26-a559-4790-8303-96aac2fee964)
I remember this working the last time I was playing before 2.0. Is this from Foreman2 side or Py side?
This is on the latest release 2.2.15.2.
Mod list:
![image](https://github.com/user-attachments/assets/f08b58ce-74a7-454f-b0f8-a7f9bbf4859e)

**Comment by AbyssalLayer** [comment]
For me i dont have any modules when using pY created preset with Foreman2. Normal preset have everything working

**Comment by DanielKote** [comment]
Right, factorio 2.0 module update edge case that I didnt notice as 'all worked fine in vanilla tests'.
Will be fixed for next release.

**Comment by AbyssalLayer** [comment]
ty <3
