### ISSUE TITLE
Productivity bonuses cannot be set

### ISSUE THREAD

**Issue by flameSla** [DanielKote/Foreman2#95]
Productivity bonuses cannot be set (https://wiki.factorio.com/Technologies):
"Steel plate productivity"
"Low density structure productivity"
"Scrap recycling productivity"
"Processing unit productivity"
"Plastic bar productivity"
"Rocket fuel productivity"
"Rocket part productivity"

**Comment by KubaJastrz** [comment]
Settings -> Graph Options -> Advanced

![image](https://github.com/user-attachments/assets/269485c1-1f89-4f49-b68e-8848519ad785)

**Comment by KubaJastrz** [comment]
But it is buggy (tested on 2.2.15.2). You have to switch to another "assembler" type for the value to be taken into calculations:

https://github.com/user-attachments/assets/8c2281ab-5877-4c98-83fd-a556276912f4

**Comment by flameSla** [comment]
When switching to another assembly machine, modules disappear, instead of 5 modules, 4 become

**Comment by flameSla** [comment]
Productivity modules have incorrect values T1=3%, T2=5%
