### ISSUE TITLE
Quality outputs only displaying normal and uncommon, not any of the higher tiers

### ISSUE THREAD

**Issue by cmoon12** [DanielKote/Foreman2#96]
Placing quality modules into an assembler making normal quality gears should output all qualities of gears (assuming legendary/epic is unlocked), but only shows normal and uncommon. This issue appears on v2.2.15.2, but is not on v2.2.15.

![Foreman2Quality](https://github.com/user-attachments/assets/7b7aaa8e-5ef0-4a60-9bdb-de7b3cd3c5cc)

**Comment by Olipro** [comment]
I tried creating the same inputs you have here and can't reproduce it.

Maybe check in `Settings` and see if you have the higher qualities disabled? 
![image](https://github.com/user-attachments/assets/5cd9d0e2-2c49-481b-8218-9eba39f1f922)

**Comment by DanielKote** [comment]
Yes, this can happen if you start a graph with 'vanilla' preset and switch to space age. For now just restart foreman after switching presets. I will fix this for next version
